#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.1.1f1_fef62e97e63b"
#define UNITY_VERSION_FULL_NICE "2019.1.1f1 (fef62e97e63b)"
#define UNITY_VERSION_BLD 16709166
#define UNITY_VERSION_DATE 1556764398
#define UNITY_VERSION_WIN "2019.1.1.16709166"
#define UNITY_VERSION_BRANCH "2019.1/staging"
